#!/usr/bin/env bash
# Transfer file `file` to a server

#If number of arguments is >= 3
if [ $# -ge 3 ]
then
    if [ $# -eq 3 ]
    then
        # No private key provided
        scp -o StrictHostKeyChecking=no $path_to_file $username@$ip:~/ 
    else
        # Private key provided
        scp -o StrictHostKeyChecking=no -i $path_to_ssh_key $path_to_file $username@$ip:~/
    fi
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi