#!/usr/bin/env bash
# Install and start nginx

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# start and configure Nginx
service nginx start
ufw allow 'Nginx HTTP'
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
sudo service nginx restart

#create index.html file and send to server
echo "Hello World!" | sudo tee /var/www/html/index.html
