#!/usr/bin/env bash
# Redirect /redirect_me to a youtube video

# Install Nginx
apt-get update
apt-get -y install nginx

# start and configure Nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

# redirect 
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default

# restart service
service nginx restart