#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Install UFW (Uncomplicated Firewall)
sudo apt-get -y install ufw

# Firewall setting
sudo ufw allow 'Nginx HTTP'

# Configure Nginx
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default

# Create index.html
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Set ownership and permissions
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html

# Modify permissions for the Nginx configuration file
sudo chmod +w /etc/nginx/sites-available/default

# Configure the redirection
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

