#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response

# Install Nginx
apt-get -y update
apt-get -y install nginx

# Firewall settings
apt-get -y install ufw
ufw allow 'Nginx HTTP'

# Create index.html and 404.html pages
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# configure Nginx with custom response header configuration:
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;

     location	 /redirect_me {
     	 return  301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
     }

     error_page	404 /404.html;
     location	/404 {
     	 root	/var/www/html;
	 internal;
     }

     add_header X-Served-By \$hostname;
}
" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
