#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer

apt-get -y update
apt-get -y install haproxy

# Backup default config HAproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure HAproxy
echo "
frontend frontend_http
    bind *:80
    mode http
    default_backend backend_http

backend backend_http
    mode http
    balance roundrobin
    server 222300-web-01 34.232.76.25:80 check
    server 222300-web-02 100.25.119.161:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# ascertain that HAproxy can be managed via an init script; start
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo service haproxy start

# verify HAproxy configuration
sleep 5  # wait for HAproxy to start
curl -Is localhost | grep "Server:\|X-Served-By:"

# restart HAproxy LB to apply changes
service haproxy restart