#!/usr/bin/env bash
# Change localhost address

# Create a copy of the original hosts file
cp /etc/hosts ~/hosts.new

# Replace the localhost with 127.0.0.2 in the copied hosts file
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.new

# Add the IP address and hostname of Facebook
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.new

# Overwrite the original hosts file with the modified copy
cp -f ~/hosts.new /etc/hosts
