#!/usr/bin/env bash
# Script to change localhost address

# Create a copy of the original hosts file
cp /etc/hosts ~/hosts.backup

# Replace the localhost with 127.0.0.2 in the copied hosts file
sed -i "s/.*localhost$/127.0.0.2 localhost/g" ~/host.backup

# Add the IP address and hostname of Facebook
sed -i "s/.*facebook.com/8.8.8.8 facebook.com/g" ~/host.backup

# Else append the line ``8.8.8.8 facebook.com/g`` to the file /etc
echo '8.8.8.8 facebook.com' >> ~/hosts.backup

# Overwrite the original hosts file with the modified copy
cp -f ~/hosts.backup /etc/hosts
