#!/usr/bin/env bash
# displays all active IPv4 IPs on the machine it’s executed on

ifconfig | awk '/ inet / {print $2}'

# ``ifconfig`` command without arguments displays only active
# network interfaces
